### ISSUE TITLE
[enhancement] Release notes would be great

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-nello#1]
First, thanks a lot for your work and the time you are investing. And of course for sharing it with the community.
Some [Release notes](https://github.com/lukasroegner/homebridge-nello/releases) would be great and maybe some trusting words in the description because of the delicate fact thats it's about a door look. ;) 
Thanks again and I very appreciate your commitment. 

Viele Grüße

**Comment by lukasroegner** [comment]
Hi @DJay-X, today I created the first release with some basic information. Moreover, the readme now contains additional information about the implementation and some words regarding security. If you have anything that you want me to add, feel free to write me.

**Comment by DJay-X** [comment]
Thanks a lot @lukasroegner 
I‘m sure people can feel now even more confident.
If you are not already in the forum [homekit.community](http://homekit.community) maybe you want to join. You are very welcome. 
Thanks again. 
Daniel
