### ISSUE TITLE
[Haustür] An error occurs while making stream request | An error occurs while making snapshot request

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-nello#11]
Thanks for updating v.0.3.1. Plugin starts without a problem now.
I already installed homebridge-camera-ffmpeg v0.1.8 and added the lines to the config.json
Unfortunately I got an error in the log. Homebridge still running but not placeholder Picture in the camera.

Thanks again.

```
Jun 16 11:27:25 raspberrypi-3BPlus homebridge[8200]: [2018-6-16 11:27:25] [Haustür] An error occurs while making stream request
Jun 16 11:27:59 raspberrypi-3BPlus homebridge[8200]: [2018-6-16 11:27:59] [Haustür] An error occurs while making snapshot request
```

```
{
            "platform": "NelloPlatform",
            "name": "Haustür",
            "username": "xxxx@gmail.com",
            "password": "xxxx",
            "lockTimeout": 5000,
            "locationUpdateInterval": 3600000,
            "exposeReachability": true,
            "doorbell": false,
            "videoDoorbell": true,
            "video": {
                "stream": "-re -i <your-url>",
                "snapshotImage": "http://via.placeholder.com/1280x720",
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30
            },
            "homekitUser": "Homebridge User"
        },
```

**Comment by AlexanderBabel** [comment]
I forgot to add the "-i" option to the snapshotImage in the readme file. ffmpeg requires that.

Also in order the fix the other message remove "<your-url>" from the stream parameter

Greetings
Alex

**Comment by AlexanderBabel** [comment]
So I will do a update for the issue with the snaptshotImage

**Comment by AlexanderBabel** [comment]
Update is out now. Just try it.

**Comment by DJay-X** [comment]
Sorry. I didn't get this.
I changed it to 
```
"video": {
                "stream": "-re -i <your-url>",
                "snapshotImage": "-i http://via.placeholder.com/1280x720",
```
Don't know in what to change the stream parameter. Removing ""???
Can I remove the whole line because I don't have a stream. But removing the whole line crashed homebridge.

Changing `"snapshotImage": "-i http://via.placeholder.com/1280x720" ` still brings the error 
```
Jun 16 12:56:59 raspberrypi-3BPlus homebridge[9448]: [2018-6-16 12:56:59] [Haustür] An error occurs while making snapshot request
Jun 16 12:57:00 raspberrypi-3BPlus homebridge[9448]: [2018-6-16 12:57:00] [Haustür] An error occurs while making snapshot request
Jun 16 12:57:07 raspberrypi-3BPlus homebridge[9448]: [2018-6-16 12:57:07] [Haustür] An error occurs while making stream request
```

If you could update the readme example configuration, I would appreciate to point me in the right direction. Thanks again.

**Comment by AlexanderBabel** [comment]
Hey,

just update the plugin version to 0.3.2 and use the old version of your config.

Greetings
Alex

**Comment by DJay-X** [comment]
Sorry Alex, I hope not to bother. But didn't work for me.
Obviously I cannot see the wood for the trees. ;)

```
{
            "platform": "NelloPlatform",
            "name": "Haustür",
            "username": "xxx@gmail.com",
            "password": "xxxx",
            "lockTimeout": 5000,
            "locationUpdateInterval": 3600000,
            "exposeReachability": true,
            "doorbell": false,
            "videoDoorbell": true,
            "video": {
                "stream": "-re -i rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov",
                "snapshotImage": "https://i.imgur.com/ZwijtUT.png",
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30
            },
            "homekitUser": "Homebridge User"
        },
```

**Comment by AlexanderBabel** [comment]
Did you installed ffmpeg? I mean the binary not the Homebridge plugin. If not take a look here: https://github.com/KhaosT/homebridge-camera-ffmpeg/wiki

**Comment by DJay-X** [comment]
Oh, sorry. Then I'm off now. Just installed `sudo npm install -g homebridge-camera-ffmpeg` @v0.1.8
I have no clue how to install and what the binary of ffmpeg is. The wiki wasn't DAU helpful to me. ;)
However I will probably dig deeper at the given time. 
Updating to nello@0.3.x seemed bigger than I thought. ;)
Thanks anyways for your friendly help so far.

**Comment by AlexanderBabel** [comment]
Alright. Another way to install is this:


```bash

apt-get install ffmpeg

```

Greetings
Alex

**Comment by AlexanderBabel** [comment]
Also you don't need to install the homebridge-camera-ffmpeg plugin

**Comment by DJay-X** [comment]
`sudo apt-get install ffmpeg`
This was the missing part. 👍🏻 Now snapshotImage works for me. No errors in the log.
Thanks a lot Alex.

Are you also on http://homekit.community ?
If not, looking forward to see you there. :)
