### ISSUE TITLE
Keine "Es hat geklingelt" Meldung

### ISSUE THREAD

**Issue by jlngnr** [lukasroegner/homebridge-nello#14]
Sorry das ich in deutsch schreibe. Aber ich brauche eine Erklärung die ich nicht erst übersetzten muss und evtl dadurch etwas falsch verstehe.
Folgendes:
Ich habe das Plugin installiert und die Daten in die Config.json richtig eingetragen. Ich bekomme auch eine Schloss in Homekit angezeigt und die Push wenn ich das Schloss öffne und es wieder geschlossen wird. 
Jedoch bekomme ich nicht die Meldung die für mich wichtig ist und zwar das es geklingelt hat.
Habe schon alles probiert. Doorbell auf True, Videodoorbell auf false. Doorbell auf false, Videodoorbell auf true. Beides auf True oder false. Kamera habe ich auch schon eingebunden als neues Gerät usw.
Aber ich bekomme diese Medung einfach nicht.
Was muss ich machen und wie muss die config aussehen damit es geht.
Bitte helft mir!
Danke

**Comment by AlexanderBabel** [comment]
Hey,

es wäre hilfreich, wenn du mal deine Config posten könntest. Am besten teste erstmal die neuste Version (v0.3.5) und wenn der Fehler weiterhin auftritt, melde dich nochmal.

Grüße
Alex

**Comment by CooperCGN** [comment]
I have the same problem, I get the push message that someone has rung but there's no button showing up. Camera and lock are in the same room, camera shows the default image so I assume ffmpeg is installed correctly.

My config looks like this:

{
            "platform": "NelloPlatform",
            "name": "nello.io",
            "username": "XXXXXXXXXXX",
            "password": "XXXXXXXXXXX",
            "lockTimeout": 5000,
            "locationUpdateInterval": 3600000,
            "exposeReachability": true,
            "videoDoorbell": true,
            "homekitUser": "HomeBridge Home"
        }

**Comment by AlexanderBabel** [comment]
I think the problem is at the side of HomeKit because the rich notification will not work every time. I have from time to time this issue too.
