### ISSUE TITLE
question: local default camera image

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-nello#18]
This might be a noob question because I am one, but can I set
"snapshotImage": "http://via.placeholder.com/1280x720"
to a local file on my Pi, somewhere in the home directory?

**Comment by AlexanderBabel** [comment]
Hey there,

This is a url to a web resource.

Greetings
Alex

**Comment by CooperCGN** [comment]
Sometimes the obvious is too far ;) I just point to my local web server.
