### ISSUE TITLE
It doesn't open the Door

### ISSUE THREAD

**Issue by llfjahn** [lukasroegner/homebridge-nello#2]
Plugin seems to work except it doesn't open the buzzer/door.

> [2018-2-22 19:08:18] [nello.io] Configuring accessory with location ID 673d50b7-681a-40b3-b9f3-6216fbeda983.
> Setup Payload:
> X-HM://0023ISZ053HB4
> [2018-2-22 19:08:19] [nello.io] Cached accessories loaded.
> [2018-2-22 19:08:19] [nello.io] Signing in.
> [2018-2-22 19:08:20] [nello.io] Signed in successfully.
> [2018-2-22 19:09:54] [nello.io] Opening door at location with ID 673d50b7-681a-40b3-b9f3-6216fbeda983.

**Comment by DJay-X** [comment]
Same here

**Comment by lukasroegner** [comment]
Sorry for the inconvenience, seems that I have forgotten the "swipe" parameter for opening the door. I added that in the latest version, feel free to update via npm and try again. I'll get my nello.io hardware today and test it throughout the day.

**Comment by llfjahn** [comment]
Now it’s working.
Danke!
