### ISSUE TITLE
How to see unlock in notification

### ISSUE THREAD

**Issue by carlsendk** [lukasroegner/homebridge-nello#21]
Do you need to have a video stream to get the unlock in notification?

I'm a little confused by you manual around doorbell and video.

My use case I have video Siedle intercom. (I havn't figured out yet how to get the video stream, I hope door bird ip upgrade with video will fix this for me).

So even though I don't have video stream to put in, I want to have an unlock option in my notification.

**Comment by AlexanderBabel** [comment]
No you don't need to have a video stream. Just use the default config.

**Comment by carlsendk** [comment]
So if I remove doorbell and videodoorbell I would be able to unlock from notification?

**Comment by AlexanderBabel** [comment]
The current default configurations exposes a motion sensor only for ring notifications.

If you want an unlock button you need to use the default ffmpeg configuration. Also you need to install ffmpeg (apt-get install ffmpeg)

Greetings
Alex

**Comment by carlsendk** [comment]
videoDoorbell (optional): If this value is set to true, a camera can be added to HomeKit (as extra accessory) and when someone rings at your door you will get a push notification with unlock button (The lock and the camera must be in the same room to see the **unlock button**). Default set to false.

**Comment by carlsendk** [comment]
Thanks I will try this. As I said it not total clear in docs what you need to set to get the unlock button in notification.

And you need to add the camera to HomeKit?

I think my issue is I have added the camera but not the ffmpeg as I don't have a camera and only what the unlock button.

It would be nice if you made a better way to achieve this without having to install ffmpeg and add a camera.

**Comment by carlsendk** [comment]
"lockTimeout": 8000,
            "locationUpdateInterval": 3600000,
			"exposeReachability": true,
            "motionSensor": true,
            "motionTimeout": 8000,
            "alwaysOpenSwitch": true,
            "videoDoorbell": true,
            "video": {
                "stream": "-re -i <your-url>",
                "snapshotImage": "http://via.placeholder.com/1280x720",
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30,
                "vcodec": "h264_omx"
            },
            "homekitUser": "Home Kit"

Should I disable motion sensor? if I want to unlock button?

**Comment by AlexanderBabel** [comment]
You can use the motion sensor independent from the camera.

**Comment by AlexanderBabel** [comment]
Is your issue still existing?

**Comment by ghost** [comment]
I need to test it if it works. i have been away on vacation.

**Comment by AlexanderBabel** [comment]
Hey there,

had you found the time to test your setup?

Greetings
Alex

**Comment by carlsendk** [comment]
I think i need a dummysteam for it to work the default url is not working

**Comment by carlsendk** [comment]
[8/22/2018, 2:49:07 PM] [nello.io] Start streaming video from undefined with 1280x720@299kBit         
[8/22/2018, 2:49:07 PM] [nello.io] An error occurs while making stream request                        
[8/22/2018, 2:49:17 PM] [nello.io] Snapshot from undefined at 480x270                                 
[8/22/2018, 2:49:17 PM] [nello.io] An error occurs while making snapshot request                      
[8/22/2018, 2:49:21 PM] [nello.io] Start streaming video from undefined with 1280x720@299kBit         
[8/22/2018, 2:49:21 PM] [nello.io] An error occurs while making stream request                        
[8/22/2018, 2:49:22 PM] [nello.io] Snapshot from undefined at 480x270                                 
[8/22/2018, 2:49:22 PM] [nello.io] An error occurs while making snapshot request                      
^[c[8/22/2018, 2:49:32 PM] [nello.io] Snapshot from undefined at 480x270                              
[8/22/2018, 2:49:32 PM] [nello.io] An error occurs while making snapshot request                      
[8/22/2018, 2:49:52 PM] [nello.io] Snapshot from undefined at 480x270                                 
[8/22/2018, 2:49:52 PM] [nello.io] An error occurs while making snapshot request                      

            "lockTimeout": 10000,
            "locationUpdateInterval": 3600000,
			"exposeReachability": true,
            "motionSensor": false,
            "motionTimeout": 10000,
            "alwaysOpenSwitch": true,
            "videoDoorbell": true,
            "video": {
				"stream": "-re -loop 1 http://via.placeholder.com/1280x720",
                "snapshotImage": "-i http://via.placeholder.com/1280x720",
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30,
                "vcodec": "h264_omx"
            },
            "homekitUser": "Home Kit"
		},

**Comment by lukasroegner** [comment]
@jcarldk have you tried to use a static image from the file system (as described in the troubleshooting section)? You can use any image on the file system, just provide an absolute path instead of the URL

**Comment by carlsendk** [comment]
Yes. But a not sure it's the correct URL. I'm running from docker with a mount folder

**Comment by carlsendk** [comment]
I think my issue is i don't have ffmpeg

Reading package lists... Done                                                                         
Building dependency tree                                                                              
Reading state information... Done                                                                     
Package ffmpeg is not available, but is referred to by another package.                               
This may mean that the package is missing, has been obsoleted, or                                     
is only available from another source                                                                 
                                                                                                      
E: Package 'ffmpeg' has no installation candidate

**Comment by lukasroegner** [comment]
Which distribution are you using in the Docker environment? I think ffmpeg is not in the Debian package lists. https://www.ffmpeg.org has a lot of documentation for all common distributions.

**Comment by carlsendk** [comment]
https://hub.docker.com/r/marcoraddatz/homebridge/

**Comment by carlsendk** [comment]
At least i know whats the problem is now. but havn't found a fix thats work yet. I think i need a different docker images to solve it

**Comment by carlsendk** [comment]
Now i got it to work, i just need to check if i can unlock from notification :-) 

https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology

And in the process i found this for synology: https://github.com/oznu/homebridge-syno-spk#how-to-install

**Comment by carlsendk** [comment]
Do you need to group them to make it work? I get the video feed, but not the unlock feature

**Comment by lukasroegner** [comment]
Both, the lock and the camera have to be in the same room.

**Comment by carlsendk** [comment]
You need to tap hold on iPhone to see it. Just close this one I got it to work. Thank for your patience :-)
