### ISSUE TITLE
Implementation of a Switch Option for Beacon Automation

### ISSUE THREAD

**Issue by sebrot330** [lukasroegner/homebridge-nello#23]
Dear collaborators,

This Homebridge plugin for nello is really great!
The only thing missing from the nello-producers point of view is the option to use a beacon instead of having to ring and waking up everybody in the flat.
Therefore I thought of using the [RoomLocator](https://www.linkdesk.com/de/locator/) of LinkDesk and putting it somewhere in my mailbox which is close to the door.
The setup using the Devices App is really easy but due to HomeKit security regulations you always have to confirm the push notification telling you if you are sure to open the lock.

Therefore it would be amazing to have the option of using a switch instead of a lock. This would allow to bypass the security and result in a complete automation without having to get your iPhone out of your pocket, unlocking and confirming the automation action.

Hopefully this issue helps others sharing the same wish of having hands free access to your door.
Thanks again for your great work @AlexanderBabel @lukasroegner !

**Comment by AlexanderBabel** [comment]
I‘ll take a look at your feature request next weekend.

**Comment by sebrot330** [comment]
Great Thanks!

**Comment by AlexanderBabel** [comment]
Unfortunately I had not enough time to look up your request. I'll do it during the coming week.

**Comment by sebrot330** [comment]
No worries :) maybe its super fast to implement, im not sure

**Comment by sebrot330** [comment]
Hi @AlexanderBabel I just wanted to let you know that I stumbled across this [homebridge-plugin](https://github.com/shexbeer/homebridge-nelloio) which does the job for me. So if you want you can close this issue.
Best regards and thanks for your help,
Sebastian

**Comment by AlexanderBabel** [comment]
Alright. I'm sorry that I haven't found the time to implement the feature. But this is also a solution. 

So I close this issue.
