### ISSUE TITLE
Webhooks do not work

### ISSUE THREAD

**Issue by lukasroegner** [lukasroegner/homebridge-nello#26]
Hi @AlexanderBabel,

I noticed some days ago that I don't get push notifications. When I restart homebridge, the connection to the backend is missing in the logs (however, no error message from socket io is shown).

Does the web hook backend work as expected?

Best regards
Lukas

**Comment by AlexanderBabel** [comment]
Should work now. OVH restarted my server without my knowledge.

**Comment by lukasroegner** [comment]
Works! Thanks for the fast reply.
