### ISSUE TITLE
Expose as stateless switch

### ISSUE THREAD

**Issue by tobiaslins** [lukasroegner/homebridge-nello#27]
It would be great if there is an settings to expose the mechanism as a stateless switch instead of a LockMechanism.

I would love this because it would be possible to open the door via Siri (Homepod) easily.
Currently when I tell my Homepod to open the door downstairs it says I need to do it on my phone due security restrictions!

Tell me what you think! :)
And thanks a lot for the library

**Comment by marcometz** [comment]
I would love this feature, too. 
Thanks for your great work so far. It works perfekt. 

Thanks a lot!

**Comment by lukasroegner** [comment]
I'm closing this now as nello is discontinued.
