### ISSUE TITLE
Could not get access token from response

### ISSUE THREAD

**Issue by CapoD** [lukasroegner/homebridge-nello#28]
Hi,

currently I have the following problem:
```
[2018-10-15 17:14:51] [CDT Nello] Error while signing in. Status Code: 401
[2018-10-15 17:14:51] [CDT Nello] Error while signing in. Could not get access token from response: {"error":"unauthorized_client"}
[2018-10-15 17:14:51] [CDT Nello] Connected to webhook backend.
```
This problem is showing up after upgrading to the last version of this plugin. I didn't change my password in Nello nor in the homebridge `config.json`. Furthermore, I get the some problem by testing with  a different account. For both accounts, I used a proper `"clientId"` provided by Nello. I double checked my login information to make sure that there is no typo.

My `config.json` looks like this:
```
...
  "platforms": [
        {
            "platform": "NelloPlatform",
            "name": "CDT Nello",
            "username": "****@***",
            "password": "******",
            "clientId": "3d*****",
            "lockTimeout": 5000,
            "locationUpdateInterval": 3600000,
            "exposeReachability": true,
            "motionSensor": true,
            "motionTimeout": 5000,
            "alwaysOpenSwitch": false,
            "homekitUser": "Home Kit"
        }
    ]
...
```

Do any other users experience this problem?

**Comment by lukasroegner** [comment]
Hi @CapoD, sorry for the delay! Please make sure that you have
- created a client ID with the same account that you configured in the config.json
- added all "response type"s for your client ID in the Nello administration UI (see README)

The response (401) indicates that communication with the Nello servers works, however, either the client ID oder the user credentials are incorrect (or not properly configured).

**Comment by CapoD** [comment]
Hi @lukasroegner,

thanks for your reply. Since the plugin was working well and then suddenly stopped, I was quite sure that my Nello API settings were right. However, this assumption was wrong. I went back to the Nello ui and checked all "response type"s and now it works again.
Thank you very much!
