### ISSUE TITLE
New post about homebridge-nello in nello blog

### ISSUE THREAD

**Issue by felixmueller** [lukasroegner/homebridge-nello#29]
Hi Lukas,

did you see the newest post in the nello blog?
https://www.nello.io/blog/how-to-connect-your-nello-one-to-homebridge/

Maybe you can add the link to your readme.

Cheers,
Felix

<img width="821" alt="nello-homebridge" src="https://user-images.githubusercontent.com/115331/47649827-bc851280-db7e-11e8-8cac-54a0830ffc33.png">

**Comment by lukasroegner** [comment]
Hi Felix, thank you so much for notifying me, I added the link to the readme.
