### ISSUE TITLE
Error while signing in. Status Code: 500

### ISSUE THREAD

**Issue by mactwin** [lukasroegner/homebridge-nello#30]
Hi after several tests, following all the instructions, I still can not activate the plug in.
I have a custom user in App, done auth in https://auth.nello.io/admin/, tested with https://auth.nello.io/client/  
and the variable are correct ....I have no idea about the problem, every start this is the error:

[nello.io] Cached accessories loaded.
[nello.io] Getting locations from nello.io.
[nello.io] Signing in.
[nello.io] Error while signing in. Status Code: 500
[2018-11-18 01:16:09] [nello.io] Error while signing in. Could not get access token from response: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\n  \"http://www.w3.org/TR/html4/loose.dtd\">\n<html>\n  <head>\n    <title>AttributeError: 'NoneType' object has no attribute 'user_id'....................

     "platform" : "NelloPlatform",
      "name" : "nello.io",
      "username": "<fgxxxxxxxxxxxxxxxxxxxxxx>",
      "password": "<axxxxxxxxxxxxxxxxxxxxxxx>",
      "clientId": "fbxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "lockTimeout": 5000,
      "locationUpdateInterval": 3600000,
      "exposeReachability": true,
      "motionSensor": true,
      "motionTimeout": 5000,
      "alwaysOpenSwitch": false,
      "homekitUser": "Homebridge"

where username is the same used in https://auth.nello.io/admin/ email field, clientId is the same and homekitUser is the same in nello app user.

thanks for support
f

**Comment by lukasroegner** [comment]
It seems that the Nello API is returning an Internal Server Error (Status Code 500). @ermalguni could help with this issue. The API should not return a 500 status code.

**Comment by mactwin** [comment]
How can I contact him?
Does he look at these traces or do I have to turn the request?

**Comment by ermalguni** [comment]
@mactwin @lukasroegner sorry for the late reply. I thought that I was watching this repo but that was not the case. Will look into it today. Seems from the error that there is something wrong with the authorization. @mactwin do you have a specific user for the API? Furthermore, can you paste, if possible, the full error that you get.

**Comment by ermalguni** [comment]
And also can you confirm that the username/password is correct. I will push a fix later today so that this 500 does not appear anymore.

**Comment by mactwin** [comment]
In the "username" variable I have the email used in https://auth.nello.io/admin/ and same story for "password" variable; in "clientId" I have paste the "Client ID" that I have in the site auth.nello.io/admin/ 

--- log rif deleted

**Comment by ermalguni** [comment]
@mactwin awesome thanks for that. I can see you in the logs but I do not want to make our conversation public so pls send an email to hello@nello.io and mention "Ermal Guni Public API" and it will be assigned directly to me. We will take it from there.

**Comment by mactwin** [comment]
mail sent this afternoon
