### ISSUE TITLE
Nello activity logs shows wrong entry "someone rang but nello didn't open"

### ISSUE THREAD

**Issue by padman74** [lukasroegner/homebridge-nello#32]
Hi.
I'm new with nello and thanks for providing this plug-in. 
When my door opens with homebridge that gave the allowance I find two messages in the nello log. First says that someone rang but nello didn't open followed by saying that I opened the door.
How can I suppress the first message?

Best regards
Volker

**Comment by lukasroegner** [comment]
Hi Volker,

Can you clarify the exact situation in which the problem occurs? You stand outside, open the Home app and unlock the lock? Or do you ring the bell to automatically open the door by the geo-distance feature of Nello?

If I use the lock in the Home app to simply trigger the buzzer of the door, there is just one entry in the history.

Best regards
Lukas

**Comment by padman74** [comment]
Hey Lukas,
I use the switch to allow people to come in by ringing the bell. I ring the bell and can open the door. But then see those 2 entries. 
Regards, Volker

**Comment by lukasroegner** [comment]
I assume you use the motion sensor provided by the plugin and an automation in the Home app that unlocks the door when someone physically rings the bell?

As you are not using the built-in geo-distance feature of Nello (which provides similar functionality for users with an account and the Nello app installed on their devices), Nello does not know that the bell rings and this request is handled properly (by the homebridge plugin).

Thus, I cannot think of a way to prevent the first entry in the activity log of Nello, I'm sorry.

**Comment by padman74** [comment]
I use the parameter exposeReachability to open the door when ringing.

**Comment by lukasroegner** [comment]
This parameter determines whether the lock should be shown as "not reachable" in the Home app if the web service of Nello is not working properly or your local network has no access to the internet.

**Comment by padman74** [comment]
I'm sorry, i mean the alwaysOpenSwitch.

**Comment by lukasroegner** [comment]
Yeah, in conjunction with an automation in the Home app. Therefore, the automation is not done via Nello, which means Nello cannot decide whether it is a valid doorbell ring or one that is handled by an automation.
