### ISSUE TITLE
motion sensor not working

### ISSUE THREAD

**Issue by JotWee** [lukasroegner/homebridge-nello#33]
The motion sensor is not working anymore. 
Does somebody else have this issue?
I’m pretty sure it worked a few weeks/months ago. Now, as I am testing again, it doesn’t work. 
Everything else with Nello works fine.

**Comment by lukasroegner** [comment]
Hi @JotWee, is this issue still present?

**Comment by JotWee** [comment]
@lukasroegner yes. I assume, you are not able to reproduce this behavior? In that case, it might be an issue with my HomeKit setup.

**Comment by lukasroegner** [comment]
Maybe @AlexanderBabel could help as he implemented the motion sensor. I'll also try to look into the issue.

**Comment by krmkrx** [comment]
Just wanted to stop by and add that I have the same problem. Occasionally on some rings, the motion sensor does not trigger. Everything else workings as expected.

**Comment by lukasroegner** [comment]
@krmkrx Do you also use the camera + lock configuration, so that you get HomeKit unlock notifications? It would be of interest if you the sensor is not working or if you also do not get an unlock notification.

**Comment by phlexx** [comment]
I also can confirm that the motion sensor is not working reliable while lock and unlock notifications seem persistant but sometimes delayed. like 3hrs later delayed.

**Comment by lukasroegner** [comment]
@phlexx Can you please try to increase the `motionTimeout` in the configuration (e.g. 30000)? There might be an issue with the rather short timeout period, in which the sensor reports motion, maybe it is too short for automations to recognize it.

**Comment by lukasroegner** [comment]
No feedback, closed.
