### ISSUE TITLE
rtsp stream resolution to high performance problem Pi3B+

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-nello#34]
I found a nice rtsp stream that works with my configuration. Unfortunately the stream doesn't come well in HomeKit. I assume the quality/size is to high and uses to much performance on the RPi 3 B+.
Is there a way to change this in the config that a lower stream/resolution is used instead? As I understand maxWidth, maxHeight is only for the snapshotImage. Which works perfect of course.

The stream is rtsp://62.113.221.8:554/danubeHotels-rtplive/camera1.stream

Thanks in advance for any help.

```
"video": {
                "stream": "-re -i rtsp://62.113.221.8:554/danubeHotels-rtplive/camera1.stream",
                "snapshotImage": "https://i.imgur.com/naQ5MuW.png",
                "maxWidth": 1280,
                "maxHeight": 720,
                "maxFPS": 30,
                "vcodec": "h264_omx"
            },
```

**Comment by lukasroegner** [comment]
I think we could change the source code of the FFmpeg plugin for the camera stream, however, it should be possible that you resize the incoming video stream in the stream option, just try

`"-re -i rtsp://62.113.221.8:554/danubeHotels-rtplive/camera1.stream -vf scale=320:240"`

Haven't checked it out yet. If it works, it's fine, otherwise, I'll try to find some time to implement another solution.

**Comment by DJay-X** [comment]
Thanks for keeping in touch. Unfortunately with -vf scale=320:240 doesn't make a difference. 
Maybe the Pi 3 B+ is to weak. Wouldn't expect it from the latest model but could be. So please don't invest any time if there is other things to do. 

![img_2293](https://user-images.githubusercontent.com/3874239/51786807-fcea3180-2169-11e9-9d1f-0ec3712b6a4e.png)

**Comment by lukasroegner** [comment]
@DJay-X I'm generating my own video stream from a relatively large image file. There is no motion, which means, encoding should not take too much CPU time. On my Pi3, this process is around 10% CPU, which is really low. Maybe the Pi3 is too weak to decode the video stream you are using and encode it again for HomeKit. Let us know, if you find a solution!
