### ISSUE TITLE
Nello open by time window, not recognised in Homebridge/HomeKit anymore

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-nello#35]
@lukasroegner @ermalguni 
Hi Guys. Hope you are doing well.
I noticed that when Nello opens the door because of a scheduled time window, the action is not recognised in HomeKit/Homebridge anymore.
What is strange, everything is working when opening the door inside of HomeKit (Eve or Home App), the door opens other iOS devices show a notification that the door was opened and also Nello App is showing a push notification that Homebridge (User) opened the door.
Only the other way around is not working, when Nello opens automatically, no info is send to Homebridge/HomeKit anymore. 
Any idea? 
Thanks in advance for the time you are investing and for your reply.

**Comment by ermalguni** [comment]
@lukasroegner can you take a look into this from your side? It seems that it might be an issue with Homebridge. If that is not the case I will take it and check the logs.

**Comment by lukasroegner** [comment]
Hi @DJay-X @ermalguni 
I haven't set up a time windows before, I'll do that and check for the response of the Nello API.
I currently also have issues with my Nello (it always thinks I entered the building, however, it is just someone ringing the bell), also happens if I'm miles away. Please give me some time to test it all out.

@ermalguni if I need your help with your internal logs, I would contact you, thank you for offering your help!

**Comment by DJay-X** [comment]
Thanks to you both. Thanks @lukasroegner I got the Feedback, that other Users facing the same issue that HomeKit ist not notified when Nello opens the door automatically because of a active time window. https://forum.smartapfel.de/forum/thread/969-nello-one-integration/?postID=49157#post49157

Something must have changed, because when I first set up everything my automation worked great, when Nello opened automatically the door, the status in Eve App was also switch to open so that my HomeKit Automation was triggered. 

Thanks for the time you are investing and for your help.

**Comment by DJay-X** [comment]
Without changing anything, in the case of a delivery with an active time window, the opening message was forwarded correctly to HomeKit today and the automation set up was triggered.
Strange... 🤔 I'll keep an eye on it for the next delivery and report.

![napkin 2 25 01 19 5 03 28 pm](https://user-images.githubusercontent.com/3874239/51757314-56e3ec00-20c3-11e9-9b31-c97bae0861f3.png)

**Comment by lukasroegner** [comment]
@DJay-X Thank you for sharing this with us. It's quite strange, as I didn't update anything.

**Comment by DJay-X** [comment]
I will close this "issue" for now, because I can't reproduce the strange behaviour. Since a couple of days and with an active time window in nello, HomeKit triggers everything right.
Will get back, if something wrong happens again.
Thanks guys.

**Comment by DJay-X** [comment]
Hi Guys. First, I hope you are doing well.

Unfortunately I am facing the same issue again "Nello open by time window, not recognised in Homebridge/HomeKit anymore" since a couple of days. Documented today, 09.09.2019

Time window is active in nello App. The door opens by nello and all activities are showing up in the activity feed in nello app. But HomeKit Homebridge Plugin is not noticing the opening. 
And because of this issue, no automation is working either. 

The other way around when I open the door in HomeKit, nello opens and this is shown in the activity feed correctly. 
The information seems to be lost only from nello -> to HomeKit.
Manual opening in the nello app is also not noticed by HomeKit. So it's not only active time window.
I checked https://nello.statuspage.io/# but there is no incident.

And as usually no change on homebridge, update or setup. Last week it worked like expected, the past couple of days not. :/ 
I hope you can help or have a look @ermalguni @lukasroegner 

Thanks in advance for your time guys.

![Napkin 2 09 09 19, 2 22 04 PM](https://user-images.githubusercontent.com/3874239/64530381-48260e80-d30d-11e9-91b5-1a28c385013a.png)

**Comment by DJay-X** [comment]
Again today, 10.09.2019 - 13:19
Nello opened the door because of active time window, but no communication to the Plugin/HomeKit. Hope this helps to investigate. Thx.
![Napkin 2 10 09 19, 1 44 24 PM](https://user-images.githubusercontent.com/3874239/64611266-59385380-d3d1-11e9-8349-dc8101a84ed2.png)

**Comment by lukasroegner** [comment]
@DJay-X Can you provide snippets from your log file, so that we can check if the plugin has issues or the Nello server?

**Comment by DJay-X** [comment]
Thanks for your reply. Unfortunately at the moment I'm not able to provide a log from my Pi/Homebridge.

But as mentioned, nothing changed on my side in the last days. No news HW setup. No update on the Pi. No new npm or node. Didn't touched the config. 
Besides as mentioned, "out" from HomeKit to nello is recognised. But not the other way around from nello to homebridge plugin. 

Strange is that we are facing the exact issue several times in the past. An it had never anything to do with the plugin as I can remember. I'd be curious if there have been any updates to the Nello backend lately.

**Comment by ermalguni** [comment]
@DJay-X @lukasroegner I will take a look into our logs today or tmrw latest and maybe I see something. Will keep @DJay-X posted in the issue he created with us and you @lukasroegner here.

**Comment by DJay-X** [comment]
Another Example
Do. 12/09/2019, 17:27
Active Time Window DHL Do. 12/09 05:05 PM - 05:30 PM

Fr. 13/09/2019, 12:11 and 12:13
Active Time Window DHL Do. 13/09 09:00 AM - 05:00 PM

Fr. 13/09/2019, 13:07
Active Time Window DHL Do. 13/09 09:00 AM - 05:00 PM

Fr. 13/09/2019, 15:33
Active Time Window DHL Do. 13/09 09:00 AM - 05:00 PM

Nello opened the door. No Info forwarded to Plugin/HomeKit. No Automation started.

**Comment by DJay-X** [comment]
As trough by chance or probably after some changes by @ermalguni it seems to work again now as expected.

16.09.2019 11:05 and 12:11 
18.09.2019 12:33 and 16:01

The door was opened by nello because of active time window and also now HomeKit/homebridge-nello worked.
HomeKit was noticing the opening of the door by nello, send a Notification and also my automations started by that trigger.

Thanks to you both for the help and support. And of course again for this great plugin. 
Wouldn't want to miss nello as a feature in my Smart Home and this Plugin in combination makes it perfect with HomeKit. Hope the journey will go on with you guys. 
Thanks again.
