### ISSUE TITLE
Homebridge registering a wehook

### ISSUE THREAD

**Issue by ermalguni** [lukasroegner/homebridge-nello#37]
@lukasroegner @AlexanderBabel we have had a few customers having issues with their webhooks not being called. After checking the logs I saw that their webhooks get updated to something like this: https://nello.alexdev.de/callback/..... Furthermore in the connectWebhook.js in line 7 there is a socket connection to https://nello-socket.alexdev.de. It seems like the homebridge plugin is registering a webhook with the user's locations and that all the notifs go through the proxy at alexdev.de.

Can you guys tell me if my guess is wright? 

Also, on a privacy note: Do the users know that the homebridge messages go through a proxy?

**Comment by lukasroegner** [comment]
@ermalguni thank you for letting us know. Is the issue resolved on your side? The plugin uses a relay service hosted by @AlexanderBabel, the code is also open sourced at https://github.com/AlexanderBabel/nello-backend. This is stated in the security section of the README.

The initial implementation used another webhook-to-websocket provider, however, it was not as reliable as @AlexanderBabel's solution. We are glad that you provide a public API for Nello and that there is any way of receiving events. However, web hooks are not the ideal solution for the integration into server applications that run in a private network (NAT, firewall, etc.).

**Comment by ermalguni** [comment]
@lukasroegner thanks for the the explanation. Now it is more clear. 

Just one more question: how frequently does the plugin set the webhook? Is it only one or does it perform some kind of check at regular intervals? We had a user that was setting the webhook but somehow it got reset to one of the https://nello.alexdev.de/... ones. 

We have created a low prio feature request to have webhooks per location and user. Currently you can set only a per location webhook.

**Comment by lukasroegner** [comment]
There is no interval, at which the webhook is updated. Reasons for updating might be a lost connection to the relay server or a restart of homebridge.

Please tell us as soon as you have implemented the new feature, we would like to implement it as soon as possible.
