### ISSUE TITLE
Homebridge Crash after reboot without remote access

### ISSUE THREAD

**Issue by TonistarNo1** [lukasroegner/homebridge-nello#38]
Hallo Zusammen,
ich habe das Problem, dass wenn ich meine Homebridge neu starte und mir der Internetzugriff fehlt, Nello keine Daten aus dem Internet holen kann und damit den ganzen Startvorgang der Homebridge beendet, bzw. neu startet. Dieser Vorgang wird so oft wiederholt bis Nello wieder Internetzugriff hat und erst dann kann ich die Homebridge wieder im HomeKit nutzen. Gibt es eine Möglichkeit den Abbruch bei fehlendem Internet zu unterbinden?
Liebe Grüße, Toni

**Comment by lukasroegner** [comment]
Hi Toni, you're right, we should add a timeout for connecting to the nello API and the WebSocket relay service... @AlexanderBabel, could you take a look at it?

**Comment by AlexanderBabel** [comment]
Yeah I can do that.

**Comment by TonistarNo1** [comment]
Thank you for the fast answer. I'm looking forward to the update! Otherwise, your plugin works really great and is a much more comfortable access to control the nello. Thanks for that!

**Comment by AlexanderBabel** [comment]
I released an updated version. The issue should be fixed now.

If not please reply to this thread in the next days. Otherwise, I'll close this issue after some days passed.

**Comment by TonistarNo1** [comment]
Terrific! Thanks for the quick update. Unfortunately, I am back home on Monday and can only then carry out the update and test it. But then I'll let you know as soon as possible.

**Comment by TonistarNo1** [comment]
OK. The way it looks, everything works without Internet. Thank you so much for your quick help!
