### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by henkhb** [lukasroegner/homebridge-nello#39]
Is there an Server issue, or change in API?
My installation stopped working.

[4/3/2019, 8:21:39 PM] [nello.io] Connected to webhook backend.
[4/3/2019, 8:21:39 PM] [nello.io] Updating webhook for door with ID xxx  to https://nello.alexdev.de/callback/lilu-cowew-imjizul-nimgati-oc-7435.
[4/3/2019, 8:21:39 PM] [nello.io] Updating webhook failed. Status Code: 500
[4/3/2019, 8:21:39 PM] [nello.io] Retry signing in and updating webhook again.

**Comment by Strike2001** [comment]
same here

**Comment by AlexanderBabel** [comment]
It's an error from the Nello API. Normally, a restart of your homebridge instance should be enough to get a successful web hook update.

**Comment by henkhb** [comment]
Restart does not help. Seems to be a server issue. Today it works again.
I informed nello team about this.

**Comment by lukasroegner** [comment]
Seemed to be a temporary server issue at Nello, @ermalguni?

**Comment by ermalguni** [comment]
Hey guys, it is our rate limiter. It seems that a few clients are hitting the Public API quite a lot and the rate limiter is stopping the requests. Can you check how frequently you are requesting?

As an example: today from 02:00AM-02:59AM we had 1500 rate limited events.

**Comment by Strike2001** [comment]
it is not the public api of nello ( i use the api with a smart hub too and this runs )  , maybe the backend from alex has an error 

Von meinem iPhone gesendet

**Comment by Strike2001** [comment]
normal ( update intervall = 3600000

Von meinem iPhone gesendet

**Comment by henkhb** [comment]
Same here. But had some restarts due to updates.

**Comment by lukasroegner** [comment]
Seemed to be an issue with the webhook relay service, feel free to re-open if issue still exists.
