### ISSUE TITLE
Homebridge crashing due to activity/location update introduced with 0.1.6.

### ISSUE THREAD

**Issue by krmkrx** [lukasroegner/homebridge-nello#4]
Hey there. My homebridge keeps crashing after updating to the most recent version of your plugin. I think the culprit is the newly introduced polling features for activity/location. Here is the log:

> Mar 26 19:32:52 raspberrypi homebridge[11865]: [2018-3-26 19:32:52] [nello.io] Getting activity for door at location with ID xxx.
> Mar 26 19:32:52 raspberrypi homebridge[11865]: /usr/local/lib/node_modules/homebridge-nello/index.js:385
> Mar 26 19:32:52 raspberrypi homebridge[11865]: for (var i = 0; i < body.activities.length; i++) {
> Mar 26 19:32:52 raspberrypi homebridge[11865]: ^
> Mar 26 19:32:52 raspberrypi homebridge[11865]: TypeError: Cannot read property 'length' of undefined
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at Request._callback (/usr/local/lib/node_modules/homebridge-nello/index.js:385:41)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at Request.self.callback (/usr/local/lib/node_modules/homebridge-nello/node_modules/request/request.js:186:22)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at Request.emit (events.js:127:13)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-nello/node_modules/request/request.js:1163:10)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at Request.emit (events.js:127:13)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nello/node_modules/request/request.js:1085:12)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at Object.onceWrapper (events.js:219:13)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at IncomingMessage.emit (events.js:132:15)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at endReadableNT (_stream_readable.js:1101:12)
> Mar 26 19:32:52 raspberrypi homebridge[11865]: at process._tickCallback (internal/process/next_tick.js:152:19)
> Mar 26 19:32:52 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
> Mar 26 19:32:52 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
> Mar 26 19:32:52 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

However, after editing my config to disable the new functions:

> "locationUpdateInterval":0,
> "activityUpdateInterval":0,
> "exposeReachability":false

homebridge and homebridge-nello work as expected. Any clue on why this is happening? Running homebridge with npm@5.8.0 and node@9.6.1.

**Comment by lukasroegner** [comment]
I'm sorry that the new version does not work properly for you. I enhanced the error handling for getting the activities. Could you update to version 0.1.7 and enable the `activityUpdateInterval` again? You will get detailed information on what is wrong with the activities. With this output I hope I can fix the issue.

Another thing I can think of is: does the account that you created for the plugin have administrator access?

**Comment by krmkrx** [comment]
I updated to 0.1.7 and everything is working as expected now:

> Mar 27 19:41:59 raspberrypi homebridge[10540]: [2018-3-27 19:41:59] [nello.io] Got locations from nello.io.
> Mar 27 19:42:09 raspberrypi homebridge[10540]: [2018-3-27 19:42:09] [nello.io] Getting activity for door at location with ID xxx.
> Mar 27 19:42:10 raspberrypi homebridge[10540]: [2018-3-27 19:42:10] [nello.io] Got activity for door at location with ID xxx.

Kind of unfortunate now, as I am unable to reproduce yesterdays error for you. The account used by the plugin always had administrator access. I will reopen this issue should the problem appear again. Thank you.

**Comment by krmkrx** [comment]
Hello, I am reopening. Today I got the following error:

> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting locations from nello.io failed. Status Code: 502
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting locations from nello.io failed. Could not get locations from response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Retry signing in and getting locations again.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting locations from nello.io.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Signing in.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting activity for door at location with ID 17bdc333-5372-481a-810f-0ec48a280da0 failed. Status Code: 502
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting activity for door at location with ID 17bdc333-5372-481a-810f-0ec48a280da0 failed. Could not get activity from response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Retry signing in and getting activity again.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Error while signing in. Status Code: 502
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Error while signing in. Could not get user information from response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"

This all happened during me being away from home today. This error occured, too:

> Mar 28 18:36:11 raspberrypi homebridge[23075]: [2018-3-28 18:36:11] [nello.io] Getting activity for door at location with ID 17bdc333-5372-481a-810f-0ec48a280da0.
> Mar 28 18:36:11 raspberrypi homebridge[23075]: [2018-3-28 18:36:11] [nello.io] Getting activity for door at location with ID 17bdc333-5372-481a-810f-0ec48a280da0 failed. Could not get activity from response: {"result":{"message":"429: Too Many Requests","status":"429"}}
> Mar 28 18:36:11 raspberrypi homebridge[23075]: [2018-3-28 18:36:11] [nello.io] Retry signing in and getting activity again.

Config uses your default values.

**Comment by krmkrx** [comment]
Hello, I am reopening. Today I got the following error:

> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting locations from nello.io failed. Status Code: 502
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting locations from nello.io failed. Could not get locations from response: "\r\n<title>502 Bad Gateway</title>\r\n<body bgcolor="white">\r\n502 Bad Gateway\r\nnginx\r\n\r\n\r\n"
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Retry signing in and getting locations again.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Getting locations from nello.io.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Signing in.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Retry signing in and getting activity again.
> Mar 28 17:05:11 raspberrypi homebridge[23075]: [2018-3-28 17:05:11] [nello.io] Error while signing in. Status Code: 502

> Mar 28 18:36:11 raspberrypi homebridge[23075]: [2018-3-28 18:36:11] [nello.io] Getting activity for door at location with ID xxx.
> Mar 28 18:36:11 raspberrypi homebridge[23075]: [2018-3-28 18:36:11] [nello.io] Getting activity for door at location with ID xxx failed. Could not get activity from response: {"result":{"message":"429: Too Many Requests","status":"429"}}
> Mar 28 18:36:11 raspberrypi homebridge[23075]: [2018-3-28 18:36:11] [nello.io] Retry signing in and getting activity again.

Config uses your default values.

**Comment by lukasroegner** [comment]
As you can see in the output, the nello.io server replies with "Too Many Requests". I'm currently experimenting with reasonable values for polling the service, however, it seems that we have to wait for the official public API to get the events from nello.io.

At the moment, I suggest to explicitly disable the polling mechanism:

```
"locationUpdateInterval": 3600000,
"activityUpdateInterval": 0
```

**Comment by lukasroegner** [comment]
Public API now available. Please update the homebridge plugin. New features for doorbell service will be added soon.
