### ISSUE TITLE
No VideoDoorBell configurtion needed for Push notification with unlock button

### ISSUE THREAD

**Issue by thecem** [lukasroegner/homebridge-nello#44]
Hi Guys, it is not needed to configure a camera via the homebridge-nello plugin to get a push notification with unlock button. The lock and the camera must be in the same room to see the unlock button, but the camera could be another one like a Netatmo or Nest (via homebridge-nest-cam plugin). In my case I have 3 cams an i get randomly the cam pictures in the push notification and the unlock button works every time!

Realy nice feature, since no VideoDoorBell (with HomeKit Support) have the possibillity to open a door.

Thanks for this plugin!

**Comment by lukasroegner** [comment]
You're right, you just have to have a camera and the lock in the same room. I don't have a real camera in my apartment, thus I'm using the option of this plugin to expose a fake camera (it just shows the Nello icon as stream from an image file).

Without this fake camera, I wouldn't get unlock notifications. Didn't know, that it shows random camera streams if you have multiple cameras, thank for the info!
