### ISSUE TITLE
Removing Username/Password from config file brakes the plugin

### ISSUE THREAD

**Issue by MGPhil** [lukasroegner/homebridge-nello#45]
Hi, sorry if I may ask a question that is answered already but I could not found it after some search in the issues.
I tried to use the plugin with clientId and clientSecret only like in the readme (Default configuration (with a motion sensor for ring notifications)).
In the startup logs of homebridge the plugin always requests the username and password and was not working at all (nothing added to Apple Home) so I added username and password in the config file.
After adding above everything works like it should.
Could somebody tell me what is the benefit of having clientId/clientSecret if I still need a plain password and user in an unsecured file?

**Comment by lukasroegner** [comment]
Maybe you have to change the settings in the Nello admin interface, so that the clientId/clientSecret flow is enabled. @nihalgonsalves created the PR, maybe he can help?

**Comment by nihalgonsalves** [comment]
@MGPhil You need to set `"authType": "client"`.

From the README:

> authType (optional): the method of authentication, either "password" or "client". This is set to "password" for backwards compatibility with previous versions of this plugin, but it is recommended to use the "client" method to avoid having to keep a username and password in plaintext in the configuration.

**Comment by MGPhil** [comment]
Hi @lukasroegner, Hi @nihalgonsalves, thats clear and is done in my config:
——————
{
      "homekitUser" : "XXX",
      "clientId" : "XXX",
      "alwaysOpenSwitch" : true,
      "exposeReachability" : true,
      "lockTimeout" : 5000,
      "authType" : "client",
      "motionSensor" : true,
      "clientSecret" : "XXX",
      "motionTimeout" : 5000,
      "password" : "XXX",
      "platform" : "NelloPlatform",
      "username" : "XXX",
      "name" : "nello.io",
      "locationUpdateInterval" : 3600000
    }
———————
XXX are of course filled with the right inputs,
if I remove one of the two (username or password) on homebridge startup i get following „error“:
sudo homebridge -U /root/.homebridge
[2019-5-1 15:54:29] ---
[2019-5-1 15:54:30] Loaded plugin: homebridge-nello
[2019-5-1 15:54:30] Registering platform 'homebridge-nello.NelloPlatform'
[2019-5-1 15:54:30] ---
[2019-5-1 15:54:31] [nello.io] Initializing NelloPlatform platform...
[2019-5-1 15:54:31] [nello.io] Homebridge API available.
[2019-5-1 15:54:31] [nello.io] Configuring accessory with location ID XXX.
[2019-5-1 15:54:31] [nello.io] Cached accessories loaded.
[2019-5-1 15:54:31] [nello.io] Getting locations from nello.io.
[2019-5-1 15:54:31] [nello.io] No username for nello.io provided. Please make sure to create a dedicated nello.io account for this homebridge plugin.
[2019-5-1 15:54:32] [nello.io] Connected to webhook backend.
[2019-5-1 15:54:33] Homebridge is running on port XXX.

Homebridge starts but nello is not added.

**Comment by nihalgonsalves** [comment]
@MGPhil Looks like you're using an older version of `homebridge-nello`. Check your dependencies and/or run `npm install homebridge-nello` again (with `-g` or `--save` as appropriate).

**Comment by lukasroegner** [comment]
@MGPhil did you install the plugin via npm? The version on npm is not the latest version (to which the clientId/clientSecret flow belongs). I'll update the npm version as soon as I've tested another PR from @nihalgonsalves.

**Comment by nihalgonsalves** [comment]
Ah yes, if it isn't published yet, that would be it :)

**Comment by MGPhil** [comment]
Yes I install everything for my homebridge from npm (2 days ago),
is that not the „normal“ way of doing it?

Means when you update npm and I update my homebridge plugin I can remove username/password?
If so were/how can I see that npm and github are not in sync?

**Comment by nihalgonsalves** [comment]
Yes, using npm is definitely the norm. @lukasroegner I've seen other packages put a warning at the top of the README and a link to the version of the README corresponding to the package that is published on npm.

**Comment by lukasroegner** [comment]
@MGPhil you have to explicitly update your npm packages as a developer. The README on npm is the old one (you may have followed the link to GitHub and read it there). @nihalgonsalves, we don't update the plugin this often, usually, we directly publish a new version on npm.

**Comment by MGPhil** [comment]
Yes exactly @lukasroegner normally I google for nice new homebridge plugins come then to npm website and klick on the link to github were I read the manual an install everything over npm.
Don‘t know why npm and not github is shown in google search.

When can I expect the new version to be on npm?
Or is there an „easy“ way to update the npm download from me with the github version here?

**Comment by lukasroegner** [comment]
@MGPhil new version is on npm.

**Comment by lukasroegner** [comment]
@MGPhil btw, you can also install npm packages directly from GitHub, see https://docs.npmjs.com/cli/install
