### ISSUE TITLE
[Enhancement] Repository 404

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-nello#46]
npm https://www.npmjs.com/package/homebridge-nello is still linked to GitHub Repository to https://github.com/lukas.roegner/homebridge-nello which gives 404.
Correct is https://github.com/lukasroegner/homebridge-nello
😉
Noticing this "issue" when using config-ui-x and on npm website.

Thanks for your ongoing work and updates with this plugin.
Wouldn't want to miss it. Makes my nello one complete. 👍 

![Napkin 2 19 05 19, 12 21 04 PM](https://user-images.githubusercontent.com/3874239/57980852-bed28f80-7a30-11e9-81e4-f077666fd529.png)

**Comment by lukasroegner** [comment]
Thanks for reporting, fixed!
