### ISSUE TITLE
nello working with HomeKit after 18.10.2019 Bankruptcy of LOCUMI LABS GmbH 

### ISSUE THREAD

**Issue by DJay-X** [lukasroegner/homebridge-nello#48]
@ermalguni @lukasroegner 
First of all, so sorry to hear about the bankruptcy of LOCUMI LABS GmbH. 😔
All the best to the girls and guys there. Wish them all the best for their new way. 

Anyway, you think there is a chance to keep nello working locally and with homebridge-nello?
Last words from nello Team was.. "So that you can still use your nello one, we are currently working on a solution, which we will introduce to you shortly. 🤗"

Maybe there is a glimpse of hope for us customers?

@lukasroegner As an external, are you involved or trying to reach out to them to also keep your Plugin alive? Would be awesome. 

Thanks to you.

**Comment by oleg-dmytrenko** [comment]
I hope it will be possible to keep Nello One alive via Homebridge. I am sure there are a lot of users out there who also feel that way.

**Comment by lukasroegner** [comment]
@DJay-X
If the nello Team provides a documented solution to communicate with the nello One locally, we can implement it. 

Personally, I don't think that we will get a pure local solution, as this would require some kind of firmware update for the nello, which is not possible.

Maybe (parts) the backend will be open-sourced so that you can run a local web server and change DNS settings in your router.

**Comment by DJay-X** [comment]
Thanks for your reply and the detail on information.

I think I probably shout change to Nuki Opener instead. 🤔 You already provide a Plugin for that. Aren't you?

**Comment by lukasroegner** [comment]
Yes, I pre-ordered the Nuki Opener just to check it out. Users report that it works fine, I haven‘t tested it out for more than two days as my intercom is not working correctly at the moment and I have to wait for the landlord to get it fixed.

**Comment by DJay-X** [comment]
Hmm.. However, thanks a lot if you consider to still update this nello plugin, if something is possible after 18.10. from the side of nello. Will see what they announce finally before shutting down completely. 

I join you in the Thread on forum.smartapfel.de for ongoing conversation on Nuki.

**Comment by nihalgonsalves** [comment]
FYI: Looks like the API is already down (the admin/token UI is unavailable and the accessory shows as "Unknown" in Homebridge).

Looks like Webhooks are still being processed though. I get unlock events via HomeKit.

If someone wants to continue with reverse-engineering the Nello MQTT API, here's a reference: https://hypfer.de/blog/2018/12/04/wie-man-ein-nello-one-nicht-von-der-cloud-befreit/

For authentication you need a valid MQTT client ID, but no username/password. I cannot figure out what the message payloads are encoded as. Let's hope Nello releases something / documentation / etc, as they hinted in their email.

**Comment by DJay-X** [comment]
Update from today 16th Oct. Probably to everyone but never know. 

![Bildschirmfoto 2019-10-16 um 12 29 07](https://user-images.githubusercontent.com/3874239/66911671-4ab50b80-f011-11e9-988b-a5f69e8e7adb.png)

**Comment by Karrypto** [comment]
Hi guys, @lukasroegner  is it possible to use private API instead ? I still can use nello in openhab with pynello and private API (https://github.com/pschmitt/pynello). Looks like public api is down but private works fine so far

**Comment by lukasroegner** [comment]
@Karrypto To be honest, I don't want to waste time implementing the private API (which I used in the early days of this plugin) if we don't know you whether Nello is shutting down the servers in two or three weeks. The message posted by @DJay-X only mentions that they will keep the servers running for some time...they don't tell for how long.

**Comment by DJay-X** [comment]
You all probably received it, so just for the record.
@lukasroegner Any chance you could get in touch with nello if also the previous solution with your plugin will work again? 
Thanks for your time.

> Hi Daniel,
> 
> wir haben gute Neuigkeiten, die wir natürlich sofort mit Dir teilen möchten! Die Reise von nello geht weiter – hierzu werden wir uns mit dem Team von SCLAK zusammenschließen. Der neue Eigentümer SCLAK wird der italienische Anbieter für Smart-Home-Produkte sein. Dieser passt perfekt zu nello.
> 
> Damit Du auch zukünftig dein nello one verwenden kannst, wird es in Kürze ein Update der App geben.
> 
>  Da uns hierbei deine Daten besonders wichtig sind, wirst Du im Zuge dieses Updates aufgefordert, deine Zustimmung zur Übertragung deiner Kundendaten an SCLAK zu erteilen. Nur mit deiner Zustimmung kann die weitere Nutzbarkeit Deines nello one sichergestellt werden. Ohne Datenübertragung wird die Funktionsfähigkeit deiner App auslaufen, was wir sehr bedauern würden.
> 
> Du bleibst damit Herr Deiner Daten. Und eine einmal erklärte Zustimmung kann von Dir natürlich auch jederzeit – mit Wirkung für die Zukunft – widerrufen werden. Aber wir hoffen natürlich, dass Du uns als begeisterter nello-Nutzer erhalten bleibst und auch in Zukunft den Weg gemeinsam mit uns beschreitest.
> 
>  Viele Grüße von nello

> Hi, Daniel,
> 
> we have good news, which we would like to share with you immediately! The journey of nello continues - we will join forces with the team of SCLAK. The new owner SCLAK will be the Italian supplier of smart home products. This fits perfectly to nello.
> 
> So that you can also use your nello one in the future, there will be an update of the app shortly.
> 
> Since your data is particularly important to us, you will be asked to give your consent to the transfer of your customer data to SCLAK in the course of this update. The continued usability of your nello one can only be guaranteed with your consent. Without data transfer, the functionality of your app will expire, which we would regret very much.
> 
> You thus remain the master of your data. And once you have given your consent, you can of course revoke it at any time - with effect for the future. But of course we hope that you will stay with us as an enthusiastic nello user and that you will continue to walk the path together with us in the future.
> 
> Many greetings from nello

Translated with www.DeepL.com/Translator

**Comment by lukasroegner** [comment]
@DJay-X Sorry for the late reply. I'm not using the nello anymore, however, I want to implement a fix if nello provides a solution. Any news from nello?

**Comment by sleepyarmistice** [comment]
Sorry to butt in, but there hasn’t been any new news. Lately, though, I’ve been using the old version of the plugin from before the API became available. It works most of the time, but occasionally gets shut out by Nello for like eight hours for making too may requests. I think that if there was a way to reduce the frequency of requests made, then this could be a good solution.

**Comment by lukasroegner** [comment]
I'm closing this now as nello is discontinued. If anyone has further information regarding the new owner and a possible future of this project, feel free to reopen.
