### ISSUE TITLE
Public API now available

### ISSUE THREAD

**Issue by felixmueller** [lukasroegner/homebridge-nello#5]
Time for a full featured rewrite?

https://nellopublicapi.docs.apiary.io/

Cheers,
Felix

**Comment by lukasroegner** [comment]
Hi Felix,
Finally! Thank you for your notification, I was checking the nello.io website every two days for the announcement. Expect a new version within the next week!

**Comment by AlexanderBabel** [comment]
Any updates?

**Comment by lukasroegner** [comment]
Plugin now uses the Public API. Please update the homebridge plugin.
