### ISSUE TITLE
Retrieving Client ID

### ISSUE THREAD

**Issue by adnanshah87** [lukasroegner/homebridge-nello#50]
Hi Lukas,

Is it possible to retrieve Client ID and key without the website mentioned below? It seems to be off for several weeks. Any alternative routes?

Thank you in advance

Referring to:

IMPORTANT: Please visit https://auth.nello.io/admin/ and sign in with your username and password that you also use in the nello.io app.

**Comment by lukasroegner** [comment]
Hi @adnanshah87,

Honestly, I don't know. Nello has been discontinued, it still works for some people that created the data earlier. I've switched to the Nuki Opener some time ago, thus there is no active development in this repository.

I also recommend to not use Nello anymore as there seemed to be issues with devices that always opened the door when someone rang the bell.
