### ISSUE TITLE
A lot of calls to nello-socket.alexdev.de

### ISSUE THREAD

**Issue by vovayakgh** [lukasroegner/homebridge-nello#51]
It seems that plugin is doing a lot of calls to nello-socket.alexdev.de. I got around 53000 calls a day. There should be some connection timeout implemented. It should be enough to call once a sec or every 2-3 sec.

**Comment by lukasroegner** [comment]
Hi @vovayakgh, the plugin is no longer active developed or maintained. Does your nello device still work?

**Comment by oleg-dmytrenko** [comment]
After a few days of downtime, my Nello works again.

**Comment by vovayakgh** [comment]
Yes, all is working fine except notifications to iPhone. And then as i have written, homebridge plug-in generates quite a number of DNS requests, subsequently I can assume also calls to the services.

**Comment by lukasroegner** [comment]
@vovayakgh The service at nello-socket.alexdev.de is a webhook relay, which means that webhooks from the nello server are tunneled via a web socket to your local Homebridge instance.

I think that the requests that you mentioned are simply traffic of this tunnel, not real HTTP requests.

**Comment by vovayakgh** [comment]
Well, I don't know where the problem is, but other plugins are not generating so much DNS calls. So there should be some refresh problem, or missing refresh interval from the client side.

**Comment by lukasroegner** [comment]
@vovayakgh The logs should tell you whether it is a connection issue, have you already analyzed them? From what can be seen in the source code, a log entry is created each time the socket connection has an error.

**Comment by AlexanderBabel** [comment]
Hey, 

the issue should be fixed now. My server had a problem with hosting the service. After a short investigation I found the issue and everything should work normal now.

Unfortunately I no longer have a nello one installed and therefore did not notice if the service works as expected.

If you don’t want to rely on this service, you could use the old version of the plugin which takes advantage of the private nello API. With this version there is no relay service required.

FYI: A researcher published a report of how to use nello one completely without a cloud connection: https://github.com/LFE89/nello_one_without_cloud

**Comment by vovayakgh** [comment]
Hi, thanks for your quick follow up. I can confirm that my DNS is back to normal.

**Comment by vovayakgh** [comment]
This started today again around 18:00 CET, not sure if you see any changes from your side.

**Comment by nihalgonsalves** [comment]
@vovayakgh I don't use the socket for my setup, but it does look offline - @AlexanderBabel would have to check though.

If you have the time and can change your router settings, I suggest setting up the direct webhook.

You will need to set up dynamic DNS and port-forwarding. Every router supports port-forwarding, and some even support dynamic DNS providers, but if not you can run a client on your homebridge device.

For the [config](https://lukasroegner.github.io/homebridge-nello/modules/_config_.html#nelloplatformconfig) you just need to set `publicWebhookUrl` here (and `webhookServerPort` if you want to change it from the default of `5000`).

**Comment by AlexanderBabel** [comment]
Yes, no problem. Should be solved by today evening.

**Comment by AlexanderBabel** [comment]
Should be online again! Sorry for the inconvenience, I guess I need to look for a more reliable hoster.

**Comment by vovayakgh** [comment]
All looks good now, thanks a lot!

**Comment by AlexanderBabel** [comment]
Hey, I just want to let you know, that I switched the infrastructure yesterday. I hope this will reduce the down times. 

Btw the day before yesterday was the service down again. This was the final reason to move elsewhere. Now it's hosted at AWS.

**Comment by vovayakgh** [comment]
Thanks a lot from everyone who is using NelloOne :)

**Comment by AlexanderBabel** [comment]
For more transparency, I created a status page for my hosted services. This includes the nello backend. This service checks the uptime every minute and shows incidents in real time. It is hosted separately from the main services in a different geographical region. So it will stay up if something happens to the main services.

The page is accessible through https://status.alexbabel.com

**Comment by AlexanderBabel** [comment]
FYI: 

Nello is no longer online. Therefore, the relay backend will be shutdown by the end of 2021. (31-12-2021 23:59 UTC+1)

More information about this topic can be found in [this pull request in the home assistant project](https://github.com/home-assistant/core/pull/57926).
