### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by ulumios** [lukasroegner/homebridge-nello#61]
`[10/17/2020, 22:02:25] [NelloPlatform] API error path=https://public-api.nello.io/v1/locations/faXXXXXXX/webhook/, status_code=429, response={"result":{"code":429,"success":false,"message":"30 per 1 minute"},"data":{}}`

`[10/17/2020, 22:02:27] [NelloPlatform] Rate-limited, waiting 58.431 seconds`

**Comment by nihalgonsalves** [comment]
Is this a persistent problem? The plugin normally automatically recovers within a minute.

**Comment by ulumios** [comment]
It spammed the logs for 2 days then it suddently stopped and recoverd. But the retries flooded my local DNS. I woud suggest to slow down the retry rate after a certain amount of fails.

Ps: Thx for the Plugin 👍
