### ISSUE TITLE
Crashing homebridge after removing config

### ISSUE THREAD

**Issue by CooperCGN** [lukasroegner/homebridge-nello#7]
I have two homebridge instances running, now I wanted to move the nello config from one instance to the other, since then the "old" instance keeps crashing on start up. If I uninstall the plugin it works again, whats weird is that the nello lock after the uninstall doesn't disappear from the Apple home app, instead it gives me a constant spinning wheel.

Mai 23 13:25:37 raspberrypi homebridge[1688]: Load homebridge-nello.NelloPlatform
Mai 23 13:25:37 raspberrypi homebridge[1688]: /usr/local/lib/node_modules/homebridge-nello/index.js:43
Mai 23 13:25:37 raspberrypi homebridge[1688]: platform.config.clientId = "7d9500ef-f5cb-41cf-b684-4e5345f0c48b";
Mai 23 13:25:37 raspberrypi homebridge[1688]: ^
Mai 23 13:25:37 raspberrypi homebridge[1688]: TypeError: Cannot set property 'clientId' of null
Mai 23 13:25:37 raspberrypi homebridge[1688]: at new NelloPlatform (/usr/local/lib/node_modules/homebridge-nello/index.js:43:28)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:325:30)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:8)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at Module._compile (module.js:652:30)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at Object.Module._extensions..js (module.js:663:10)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at Module.load (module.js:565:32)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at tryModuleLoad (module.js:505:12)
Mai 23 13:25:37 raspberrypi homebridge[1688]: at Function.Module._load (module.js:497:3)

**Comment by lukasroegner** [comment]
Concerning the crash of your old instance: do you have the latest homebridge version installed? The accessories are cached by homebridge, you might have to clear the cache in order to remove the nello lock from your old instance.

Please let me know if this works for you!

**Comment by CooperCGN** [comment]
Yes, I’m running the latest version. What cache? The persist directory? I just know deleting one of the two drirecrories (accessories/persist) will basically kill the whole setup.

**Comment by lukasroegner** [comment]
Yes, I mean the accessories cache. You can take a look at the cached accessories in the folder and delete the nello lock manually. Another solution would be to install the nello plugin again and provide credentials from a user that has no locks in the account.

I'm really sorry that there is no better solution!

**Comment by CooperCGN** [comment]
Is this a "problem" with the current version of homebridge? I remember deleting things from my config.json and the corresponding accessories just disappeared from my HomeKit configuration.

Anyway I got it removed by editing that cachedAccessories.json file. I will try reconfiguring it later.

**Comment by lukasroegner** [comment]
There is a difference between the "old" way of implementing accessories in homebridge and the way of dynamic platform/accessories. I used the official example plugin to start development, which dynamically adds accessories to HomeKit. 

With some plugins, you have to define the accessories that should appear in HomeKit within the config.json. Thus, if you remove those plugins and the configuration, the accessories are no longer used/visible.

Maybe there is someone who can explain it in a better way or knows how to remove accessories that have been added dynamically (even after a plugin is uninstalled), please let me know, I will adapt my code.

**Comment by CooperCGN** [comment]
Uh, I am actually a user only, no coder :)
But from what I can see there seems to be a problem with the plugin not checking whether it actually is configured in the config.json and then it is producing that error. I have one homebridge running as service with only the Philips hue plugin configured in a separate config.json and another instance for the other plugins and for testing purposes. Now when I install the nello plugin and configure it in the 'other' config.json it starts up perfectly but it crashes the hue homebridge as soon as it is restarted with the above mentioned error.

**Comment by lukasroegner** [comment]
I had a deeper look at your error message. The nello plugin does not get any configuration from homebridge, which is why the error message reads `TypeError: Cannot set property 'clientId' of null`. Are you sure that there is no typo in your config.json? It is important to have this minimum configuration:

```json
"platforms": [
        ...
        {
            "platform" : "NelloPlatform",
            "name" : "nello.io",
            ...
        }
        ...
    ]
```

**Comment by CooperCGN** [comment]
Weird, other plugins I have installed just get skipped or skip the initializing process by themselves (not sure if this is something that has to be coded into the plugin) if there’s no configuration.

As I explained to you before one of my homebridge services is only running the Homebridge-hue plugin from a separate folder with a completely seperate config.json in it. I don’t want any other plugin installed there. The other service is for all the rest and your plugin works fine there but crashes the hue one.

**Comment by lukasroegner** [comment]
Please try the latest version on the master branch, if no configuration is provided, the plugin will no longer be initialized.

**Comment by CooperCGN** [comment]
bare with me please, but how do I do this. When using the regular install command I think I still get the old version.

**Comment by lukasroegner** [comment]
I published a new version of the plugin, you can now use npm to get the latest version.
