### ISSUE TITLE
Video Doorbell service

### ISSUE THREAD

**Issue by AlexanderBabel** [lukasroegner/homebridge-nello#8]
Hey there,

do you have any new information about the upcoming video doorbell service?

Greetings
Alex

**Comment by lukasroegner** [comment]
Hi Alex,

I just moved to another flat, as soon as I installed my nello there, I'll start playing around with the video doorbell service. 

Best regards
Lukas

**Comment by DJay-X** [comment]
Hi Guys, thanks for your great work and ongoing development.
But unfortunately at the moment I don't get it. What about the doorbell and especially the videoDoorbell service? https://github.com/us09alex/homebridge-nello

At the moment I'm on v0.2.0 which is the latest release and it works very well.

But I have my nello one connected to a Siedle HTS-711-01. This device has a video screen.
How can I use a new Plugin (v0.3.0?) to get the videoDoorbell feature to work? Do I have to rewire something on the nello one to the Siedle?

Sorry for asking, but maybe not to see the wood for the trees . ☺️ I appreciate your support.
Thanks again.

**Comment by AlexanderBabel** [comment]
Hey DJay-X,

currently Nello don't support video doorbells. Therefore it is not possible to implement a real video doorbell in this plugin. Instead I implemented a fake camera accessory to have the ability to open the front door directly from the notification.

Greetings
Alex

**Comment by AlexanderBabel** [comment]
Hey DJay-X,

I updated my fork and added support for external rtsp streams. So if your manufacture provides support for this type of internet streaming you can add the stream to the camera.

Greetings
Alex

**Comment by DJay-X** [comment]
@us09alex Good to have the possibility. Thanks for your work.
Are you guys (@lukasroegner @us09alex ) working together? I think you both can easily use the synergy. I'm just wondering because the this version of the plugin is on v0.2.1 without any of the known features of videoDoorbell etc. Or are you both going separate ways?
But remember.. it's always better together. ;) 

Thanks anyways.

**Comment by AlexanderBabel** [comment]
Hey,

yes we are working together from now on.

It is currently not included because I thinks its better that @lukasroegner checks the code before the release. (four eyes principle)

Greetings
Alex
